import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Banner from "./components/ui/banner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="fixed top-0 left-0 w-full z-50">
          <Banner />
        </div>
        {children}
      </body>
    </html>
  );
}
